const PERMISSION_MARKETING = {
  LIST_ALL_ORDERS_PERSONAL: "MARKETING.LIST_ORDERS",
  LIST_ALL_ORDERS: "MARKETING.LIST_ALL_ORDERS",
  CREATE_ORDERS: "MARKETING.CREATE_ORDERS",
  UPDATE_ORDERS: "MARKETING.UPDATE_ORDERS",
  READ_DETAIL_ORDERS: "MARKETING.READ_DETAIL_ORDERS",
  GET_STATS_ORDERS: "MARKETING.GET_STATS_ORDERS",
};

export default {
  PERMISSION_MARKETING,
};
