const optionTinh : any = {
    "Thủ đô Hà Nội": {
      "Quận Ba Đình": "II",
      "Quận Bắc Từ Liêm": "II",
      "Quận Cầu Giấy": "II",
      "Quận Đống Đa": "II",
      "Quận Hà Đông": "II",
      "Quận Hai Bà Trưng": "II",
      "Quận Hoàn Kiếm": "II",
      "Quận Hoàng Mai": "II",
      "Quận Long Biên": "II",
      "Quận Nam Từ Liêm": "II",
      "Quận Tây Hồ": "II",
      "Quận Thanh Xuân": "II",
      "T.Xã Sơn Tây": "II",
      "Huyện Ba Vì": "II",
      "Huyện Chương Mỹ": "II",
      "Huyện Đan Phượng": "II",
      "Huyện Đông Anh": "II",
      "Huyện Gia Lâm": "II",
      "Huyện Hoài Đức": "II",
      "Huyện Mê Linh": "II",
      "Huyện Phúc Thọ": "II",
      "Huyện Quốc Oai": "II",
      "Huyện Sóc Sơn": "II",
      "Huyện Thạch Thất": "II",
      "Huyện Thanh Oai": "II",
      "Huyện Thanh Trì": "II",
      "Huyện Mỹ Đức": {
        "Thị trấn Đại Nghĩa": "II",
        "Xã An Mỹ": "II",
        "Xã An Phú": "II",
        "Xã An Tiến": "II",
        "Xã Bột Xuyên": "II",
        "Xã Đại Hưng": "III",
        "Xã Đốc Tín": "II",
        "Xã Đồng Tâm": "II",
        "Xã Hồng Sơn": "II",
        "Xã Hợp Thanh": "II",
        "Xã Hợp Tiến": "II",
        "Xã Hùng Tiến": "III",
        "Xã Hương Sơn": "III",
        "Xã Lê Thanh": "II",
        "Xã Mỹ Thành": "II",
        "Xã Phù Lưu Tế": "II",
        "Xã Phúc Lâm": "II",
        "Xã Phùng Xá": "II",
        "Xã Thượng Lâm": "II",
        "Xã Tuy Lai": "II",
        "Xã Vạn Kim": "III",
        "Xã Xuy Xá": "II",
      },
      "Huyện Phú Xuyên": {
        "Thị trấn Phú Minh": "III",
        "Thị trấn Phú Xuyên": "III",
        "Xã Bạch Hạ": "III",
        "Xã Châu Can": "III",
        "Xã Chuyên Mỹ": "III",
        "Xã Đại Thắng": "III",
        "Xã Đại Xuyên": "III",
        "Xã Hoàng Long": "III",
        "Xã Hồng Minh": "II",
        "Xã Hồng Thái": "III",
        "Xã Khai Thái": "III",
        "Xã Minh Tân": "III",
        "Xã Nam Phong": "III",
        "Xã Nam Tiến": "III",
        "Xã Nam Triều": "III",
        "Xã Phú Túc": "II",
        "Xã Phú Yên": "III",
        "Xã Phúc Tiến": "III",
        "Xã Phượng Dực": "III",
        "Xã Quang Lãng": "III",
        "Xã Quang Trung": "III",
        "Xã Sơn Hà": "III",
        "Xã Tân Dân": "III",
        "Xã Tri Thủy": "III",
        "Xã Tri Trung": "II",
        "Xã Văn Hoàng": "III",
        "Xã Vân Từ": "III",
      },
      "Huyện Thường Tín": {
        "Thị trấn Thường Tín": "II",
        "Xã Chương Dương": "II",
        "Xã Dũng Tiến": "II",
        "Xã Duyên Thái": "II",
        "Xã Hà Hồi": "II",
        "Xã Hiền Giang": "II",
        "Xã Hòa Bình": "II",
        "Xã Hồng Vân": "II",
        "Xã Khánh Hà": "II",
        "Xã Lê Lợi": "II",
        "Xã Liên Phương": "II",
        "Xã Minh Cường": "III",
        "Xã Nghiêm Xuyên": "II",
        "Xã Nguyễn Trãi": "II",
        "Xã Nhị Khê": "II",
        "Xã Ninh Sở": "II",
        "Xã Quất Động": "II",
        "Xã Tân Minh": "II",
        "Xã Thắng Lợi": "II",
        "Xã Thống Nhất": "III",
        "Xã Thư Phú": "II",
        "Xã Tiền Phong": "II",
        "Xã Tô Hiệu": "III",
        "Xã Tự Nhiên": "II",
        "Xã Văn Bình": "II",
        "Xã Vạn Điểm": "III",
        "Xã Văn Phú": "II",
        "Xã Vân Tảo": "II",
        "Xã Văn Tự": "III",
      },
      "Huyện Ứng Hòa": {
        "Thị trấn Vân Đình": "II",
        "Xã Cao Thành": "II",
        "Xã Đại Cường": "III",
        "Xã Đại Hùng": "III",
        "Xã Đội Bình": "III",
        "Xã Đông Lỗ": "III",
        "Xã Đồng Tân": "III",
        "Xã Đồng Tiến": "II",
        "Xã Hòa Lâm": "III",
        "Xã Hòa Nam": "III",
        "Xã Hòa Phú": "III",
        "Xã Hoa Sơn": "II",
        "Xã Hòa Xá": "II",
        "Xã Hồng Quang": "III",
        "Xã Kim Đường": "III",
        "Xã Liên Bạt": "II",
        "Xã Lưu Hoàng": "III",
        "Xã Minh Đức": "III",
        "Xã Phù Lưu": "III",
        "Xã Phương Tú": "III",
        "Xã Quảng Phú Cầu": "II",
        "Xã Sơn Công": "II",
        "Xã Tảo Dương Văn": "III",
        "Xã Trầm Lộng": "III",
        "Xã Trung Tú": "III",
        "Xã Trường Thịnh": "II",
        "Xã Vạn Thái": "III",
        "Xã Viên An": "II",
        "Xã Viên Nội": "II",
      },
    },
    "Thành phố Hồ Chí Minh": {
      "Quận 1": "II",
      "Quận 2": "II",
      "Quận 3": "II",
      "Quận 4": "II",
      "Quận 5": "II",
      "Quận 6": "II",
      "Quận 7": "II",
      "Quận 8": "II",
      "Quận 9": "II",
      "Quận 10": "II",
      "Quận 11": "II",
      "Quận 12": "II",
      "Quận Bình Tân": "II",
      "Quận Bình Thạnh": "II",
      "Quận Gò Vấp": "II",
      "Quận Phú Nhuận": "II",
      "Quận Tân Bình": "II",
      "Quận Tân Phú": "II",
      "Quận Thủ Đức": "II",
      "Huyện Bình Chánh": "II",
      "Huyện Cần Giờ": "II",
      "Huyện Củ Chi": "I",
      "Huyện Hóc Môn": "II",
      "Huyện Nhà Bè": "II",
    },
    "Thành phố Hải Phòng": {
      "Quận Đồ Sơn": "IV",
      "Quận Dương Kinh": "IV",
      "Quận Hải An": "IV",
      "Quận Hồng Bàng": "IV",
      "Quận Kiến An": "IV",
      "Quận Lê Chân": "IV",
      "Quận Ngô Quyền": "IV",
      "Huyện An Dương": "IV",
      "Huyện An Lão": "IV",
      "Huyện Bạch Long Vĩ": "V",
      "Huyện Cát Hải": "IV",
      "Huyện Kiến Thuỵ": "IV",
      "Huyện Thuỷ Nguyên": "III",
      "Huyện Tiên Lãng": "IV",
      "Huyện Vĩnh Bảo": "IV",
    },
    "Thành phố Đà Nẵng": {
      "Quận Thanh Khê": "III",
      "Quận Sơn Trà": "III",
      "Quận Ngũ Hành Sơn": "III",
      "Quận Liên Chiểu": "III",
      "Quận Hải Châu": "III",
      "Quận Cẩm Lệ": "III",
      "Huyện Hoàng Sa": "V",
      "Huyện Hòa Vang": {
        "Xã Hòa Bắc": "III",
        "Xã Hòa Châu": "III",
        "Xã Hòa Khương": "II",
        "Xã Hòa Liên": "III",
        "Xã Hòa Nhơn": "III",
        "Xã Hòa Ninh": "II",
        "Xã Hòa Phong": "III",
        "Xã Hòa Phú": "II",
        "Xã Hòa Phước": "III",
        "Xã Hòa Sơn": "III",
        "Xã Hòa Tiến": "III",
      },
    },
    "Thành phố Cần Thơ": {
      "Quận Bình Thuỷ": "II",
      "Quận Cái Răng": "II",
      "Quận Ninh Kiều": "II",
      "Quận Ô Môn": "II",
      "Quận Thốt Nốt": "II",
      "Huyện Cờ Đỏ": "II",
      "Huyện Phong Điền": "II",
      "Huyện Thới Lai": "II",
      "Huyện Vĩnh Thạnh": "II",
    },
    "An Giang": {
      "Thành phố Long Xuyên": "I",
      "Thành phố Châu Đốc": "I",
      "T.Xã Tân Châu": "I",
      "Huyện An Phú": "I",
      "Huyện Châu Phú": "I",
      "Huyện Châu Thành": "I",
      "Huyện Chợ Mới": "I",
      "Huyện Phú Tân": "I",
      "Huyện Tịnh Biên": "I",
      "Huyện Thoại Sơn": {
        "Thị trấn Núi Sập": "II",
        "Thị Trấn Óc Eo": "II",
        "Thị trấn Phú Hoà": "I",
        "Xã An Bình": "II",
        "Xã Bình Thành": "II",
        "Xã Định Mỹ": "I",
        "Xã Định Thành": "I",
        "Xã Mỹ Phú Đông": "II",
        "Xã Phú Thuận": "I",
        "Xã Tây Phú": "I",
        "Xã Thoại Giang": "II",
        "Xã Vĩnh Chánh": "I",
        "Xã Vĩnh Khánh": "II",
        "Xã Vĩnh Phú": "I",
        "Xã Vĩnh Trạch": "I",
        "Xã Vọng Đông": "II",
        "Xã Vọng Thê": "II",
      },
      "Huyện Tri Tôn": {
        "Thị trấn Ba Chúc": "I",
        "Thị trấn Tri Tôn": "I",
        "Xã An Tức": "II",
        "Xã Châu Lăng": "I",
        "Xã Cô Tô": "II",
        "Xã Lạc Quới": "I",
        "Xã Lê Trì": "I",
        "Xã Lương An Trà": "II",
        "Xã Lương Phi": "II",
        "Xã Núi Tô": "I",
        "Xã Ô Lâm": "II",
        "Xã Tà Đảnh": "I",
        "Xã Tân Tuyến": "II",
        "Xã Vĩnh Gia": "II",
        "Xã Vĩnh Phước": "II",
      },
    },
    "Bà Rịa - Vũng Tàu": {
      "Thành phố Vũng Tàu": "II",
      "Thành phố Bà Rịa": "II",
      "T.Xã Phú Mỹ": "II",
      "Huyện Châu Đức": "II",
      "Huyện Côn Đảo": "III",
      "Huyện Đất Đỏ": "II",
      "Huyện Long Điền": "II",
      "Huyện Xuyên Mộc": "II",
    },
    "Bắc Giang": {
      "Thành phố Bắc Giang": "II",
      "Huyện Hiệp Hòa": "II",
      "Huyện Lạng Giang": "II",
      "Huyện Lục Nam": "II",
      "Huyện Lục Ngạn": "II",
      "Huyện Tân Yên": "II",
      "Huyện Việt Yên": "II",
      "Huyện Yên Dũng": "II",
      "Huyện Yên Thế": "II",
      "Huyện Sơn Động": {
        "Thị trấn An Châu": "II",
        "Thị trấn Tây Yên Tử": "III",
        "Xã An Bá": "II",
        "Xã An Lạc": "II",
        "Xã Cẩm Đàn": "II",
        "Xã Đại Sơn": "II",
        "Xã Dương Hưu": "III",
        "Xã Giáo Liêm": "II",
        "Xã Hữu Sản": "II",
        "Xã Lệ Viễn": "II",
        "Xã Long Sơn": "III",
        "Xã Phúc Sơn": "II",
        "Xã Thanh Luận": "III",
        "Xã Tuấn Đạo": "II",
        "Xã Vân Sơn": "II",
        "Xã Vĩnh An": "II",
        "Xã Yên Định": "II",
      },
    },
    "Bắc Kạn": {
      "Thành phố Bắc Kạn": "II",
      "Huyện Ba Bể": "I",
      "Huyện Bạch Thông": "I",
      "Huyện Chợ Đồn": "I",
      "Huyện Chợ Mới": "I",
      "Huyện Na Rì": "I",
      "Huyện Ngân Sơn": "II",
      "Huyện Pác Nặm": "I",
    },
    "Bạc Liêu": {
      "Thành phố Bạc Liêu": "II",
      "T.Xã Giá Rai": "II",
      "Huyện Đông Hải": "II",
      "Huyện Hoà Bình": "II",
      "Huyện Hồng Dân": "II",
      "Huyện Phước Long": "II",
      "Huyện Vĩnh Lợi": "II",
    },
    "Bắc Ninh": {
      "Thành phố Bắc Ninh": "II",
      "T.Xã Từ Sơn": "II",
      "Huyện Gia Bình": "II",
      "Huyện Quế Võ": "II",
      "Huyện Thuận Thành": "II",
      "Huyện Tiên Du": "II",
      "Huyện Yên Phong": "II",
      "Huyện Lương Tài": {
        "Thị trấn Thứa": "II",
        "Xã An Thịnh": "II",
        "Xã Bình Định": "II",
        "Xã Lai Hạ": "III",
        "Xã Lâm Thao": "II",
        "Xã Minh Tân": "III",
        "Xã Mỹ Hương": "II",
        "Xã Phú Hòa": "II",
        "Xã Phú Lương": "II",
        "Xã Quảng Phú": "II",
        "Xã Tân Lãng": "II",
        "Xã Trung Chính": "III",
        "Xã Trung Kênh": "III",
        "Xã Trừng Xá": "III",
      },
    },
    "Bến Tre": {
      "Thành phố Bến Tre": "II",
      "Huyện Ba Tri": "II",
      "Huyện Bình Đại": "II",
      "Huyện Châu Thành": "II",
      "Huyện Chợ Lách": "II",
      "Huyện Giồng Trôm": "II",
      "Huyện Mỏ Cày Bắc": "II",
      "Huyện Mỏ Cày Nam": "II",
      "Huyện Thạnh Phú": "II",
    },
    "Bình Định": {
      "Thành phố Quy Nhơn": "III",
      "T.Xã Hoài Nhơn": "III",
      "T.Xã An Nhơn": "III",
      "Huyện Hoài Ân": {
        "Huyện Hoài Ân": "II",
        "Thị trấn Tăng Bạt Hổ": "III",
        "Xã Ân Đức": "III",
        "Xã Ân Hảo Đông": "III",
        "Xã Ân Hảo Tây": "III",
        "Xã Ân Hữu": "III",
        "Xã Ân Mỹ": "III",
        "Xã Ân Phong": "III",
        "Xã Ân Sơn": "II",
        "Xã Ân Thạnh": "III",
        "Xã Ân Tín": "III",
        "Xã Ân Tường Đông": "III",
        "Xã Ân Tường Tây": "III",
        "Xã Bok Tới": "II",
        "Xã Đak Mang": "II",
      },
      "Huyện Phù Cát": "III",
      "Huyện Phù Mỹ": "III",
      "Huyện Tuy Phước": "III",
      "Huyện Vĩnh Thạnh": "II",
      "Huyện An Lão": {
        "Thị trấn An Lão": "III",
        "Xã An Dũng": "III",
        "Xã An Hòa": "III",
        "Xã An Hưng": "III",
        "Xã An Nghĩa": "II",
        "Xã An Quang": "III",
        "Xã An Tân": "III",
        "Xã An Toàn": "II",
        "Xã An Trung": "III",
        "Xã An Vinh": "II",
      },
      "Huyện Tây Sơn": {
        "Thị trấn Phú Phong": "III",
        "Xã Bình Hòa": "III",
        "Xã Bình Nghi": "III",
        "Xã Bình Tân": "III",
        "Xã Bình Thành": "III",
        "Xã Bình Thuận": "III",
        "Xã Bình Tường": "III",
        "Xã Tây An": "III",
        "Xã Tây Bình": "III",
        "Xã Tây Giang": "III",
        "Xã Tây Phú": "III",
        "Xã Tây Thuận": "III",
        "Xã Tây Vinh": "III",
        "Xã Tây Xuân": "III",
        "Xã Vĩnh An": "III",
      },
      "Huyện Vân Canh": {
        "Thị trấn Vân Canh": "II",
        "Xã Canh Hiển": "III",
        "Xã Canh Hiệp": "III",
        "Xã Canh Hòa": "II",
        "Xã Canh Liên": "II",
        "Xã Canh Thuận": "II",
        "Xã Canh Vinh": "III",
      },
    },
    "Bình Dương": {
      "Thành phố Thủ Dầu Một": "I",
      "Thành phố Thuận An": "I",
      "Thành phố Dĩ An": "I",
      "T.Xã Tân Uyên": "I",
      "T.Xã Bến Cát": "I",
      "Huyện Bắc Tân Uyên": "I",
      "Huyện Bàu Bàng": "I",
      "Huyện Dầu Tiếng": "I",
      "Huyện Phú Giáo": "I",
    },
    "Bình Phước": {
      "T.Xã Phước Long": "I",
      "Thành phố Đồng Xoài": "I",
      "T.Xã Bình Long": "I",
      "Huyện Bù Đăng": "I",
      "Huyện Bù Đốp": "I",
      "Huyện Bù Gia Mập": "I",
      "Huyện Chơn Thành": "I",
      "Huyện Đồng Phú": "I",
      "Huyện Hớn Quản": "I",
      "Huyện Lộc Ninh": "I",
      "Huyện Phú Riềng": "I",
    },
    "Bình Thuận": {
      "Thành phố Phan Thiết": "II",
      "T.Xã La Gi": "II",
      "Huyện Đức Linh": "I",
      "Huyện Hàm Tân": "II",
      "Huyện Phú Quí": "III",
      "Huyện Tánh Linh": "I",
      "Huyện Tuy Phong": "II",
      "Huyện Bắc Bình": {
        "Thị trấn Chợ Lầu": "II",
        "Thị trấn Lương Sơn": "II",
        "Xã Bình An": "I",
        "Xã Bình Tân": "I",
        "Xã Hải Ninh": "I",
        "Xã Hòa Thắng": "II",
        "Xã Hồng Phong": "II",
        "Xã Hồng Thái": "II",
        "Xã Phan Điền": "I",
        "Xã Phan Hiệp": "II",
        "Xã Phan Hòa": "II",
        "Xã Phan Lâm": "I",
        "Xã Phan Rí Thành": "II",
        "Xã Phan Sơn": "I",
        "Xã Phan Thanh": "I",
        "Xã Phan Tiến": "I",
        "Xã Sông Bình": "I",
        "Xã Sông Lũy": "I",
      },
      "Huyện Hàm Thuận Bắc": {
        "Thị trấn Ma Lâm": "I",
        "Thị trấn Phú Long": "II",
        "Xã Đa Mi": "I",
        "Xã Đông Giang": "I",
        "Xã Đông Tiến": "I",
        "Xã Hàm Chính": "I",
        "Xã Hàm Đức": "II",
        "Xã Hàm Hiệp": "II",
        "Xã Hàm Liêm": "II",
        "Xã Hàm Phú": "I",
        "Xã Hàm Thắng": "II",
        "Xã Hàm Trí": "I",
        "Xã Hồng Liêm": "I",
        "Xã Hồng Sơn": "II",
        "Xã La Dạ": "I",
        "Xã Thuận Hòa": "I",
        "Xã Thuận Minh": "I",
      },
      "Huyện Hàm Thuận Nam": {
        "Thị trấn Thuận Nam": "II",
        "Xã Hàm Cần": "I",
        "Xã Hàm Cường": "II",
        "Xã Hàm Kiệm": "II",
        "Xã Hàm Minh": "II",
        "Xã Hàm Mỹ": "II",
        "Xã Hàm Thạnh": "I",
        "Xã Mương Mán": "I",
        "Xã Mỹ Thạnh": "I",
        "Xã Tân Lập": "II",
        "Xã Tân Thành": "II",
        "Xã Tân Thuận": "II",
        "Xã Thuận Quí": "II",
      },
    },
    "Cà Mau": {
      "Thành phố Cà Mau": "II",
      "Huyện Cái Nước": "II",
      "Huyện Đầm Dơi": "II",
      "Huyện Năm Căn": "II",
      "Huyện Ngọc Hiển": "II",
      "Huyện Phú Tân": "II",
      "Huyện Thới Bình": "II",
      "Huyện Trần Văn Thời": "II",
      "Huyện U Minh": "II",
    },
    "Cao Bằng": {
      "Thành phố Cao Bằng": "I",
      "Huyện Bảo Lạc": "I",
      "Huyện Bảo Lâm": "I",
      "Huyện Hạ Lang": "I",
      "Huyện Hà Quảng": "I",
      "Huyện Hoà An": "I",
      "Huyện Nguyên Bình": "I",
      "Huyện Quảng Hòa": "I",
      "Huyện Thạch An": "I",
      "Huyện Trùng Khánh": "I",
    },
    "Đắk Lắk": {
      "Thành phố Buôn Ma Thuột": "I",
      "Thị Xã Buôn Hồ": "I",
      "Huyện Buôn Đôn": "I",
      "Huyện Cư Kuin": "I",
      "Huyện Cư M'gar": "I",
      "Huyện Ea H'leo": "I",
      "Huyện Ea Kar": "I",
      "Huyện Ea Súp": "I",
      "Huyện Krông A Na": "I",
      "Huyện Krông Bông": "I",
      "Huyện Krông Búk": "I",
      "Huyện Krông Năng": "I",
      "Huyện Krông Pắc": "I",
      "Huyện Lắk": "I",
      "Huyện M'Đrắk": {
        "Thị trấn M'Đrắk": "I",
        "Xã Cư K Róa": "II",
        "Xã Cư M'ta": "I",
        "Xã Cư Prao": "II",
        "Xã Cư San": "II",
        "Xã Ea H'MLay": "II",
        "Xã Ea Lai": "II",
        "Xã Ea M' Doal": "II",
        "Xã Ea Pil": "I",
        "Xã Ea Riêng": "II",
        "Xã Ea Trang": "II",
        "Xã Krông Á": "I",
        "Xã Krông Jing": "I",
      },
    },
    "Đắk Nông": {
      "Thành phố Gia Nghĩa": "I",
      "Huyện Cư Jút": "I",
      "Huyện Đăk Glong": "I",
      "Huyện Đắk Mil": "I",
      "Huyện Đắk R'Lấp": "I",
      "Huyện Đắk Song": "I",
      "Huyện Krông Nô": "I",
      "Huyện Tuy Đức": "I",
    },
    "Điện Biên": {
      "Thành phố Điện Biên Phủ": "II",
      "Thị Xã Mường Lay": "II",
      "Huyện Điện Biên": "II",
      "Huyện Điện Biên Đông": "II",
      "Huyện Mường Ảng": "II",
      "Huyện Mường Chà": "II",
      "Huyện Mường Nhé": "II",
      "Huyện Nậm Pồ": "II",
      "Huyện Tủa Chùa": "II",
      "Huyện Tuần Giáo": "II",
    },
    "Đồng Nai": {
      "Thành phố Biên Hòa": "II",
      "Thành phố Long Khánh": "II",
      "Huyện Cẩm Mỹ": "II",
      "Huyện Định Quán": "I",
      "Huyện Long Thành": "II",
      "Huyện Nhơn Trạch": "II",
      "Huyện Tân Phú": "I",
      "Huyện Thống Nhất": "II",
      "Huyện Trảng Bom": "I",
      "Huyện Vĩnh Cửu": "I",
      "Huyện Xuân Lộc": "II",
    },
    "Đồng Tháp": {
      "Thành phố Cao Lãnh": "I",
      "Thành phố Sa Đéc": "I",
      "Thành phố Hồng Ngự": "I",
      "Huyện Cao Lãnh": "I",
      "Huyện Châu Thành": "II",
      "Huyện Hồng Ngự": "I",
      "Huyện Lấp Vò": "I",
      "Huyện Tam Nông": "I",
      "Huyện Tân Hồng": "I",
      "Huyện Thanh Bình": "I",
      "Huyện Tháp Mười": "I",
      "Huyện Lai Vung": {
        "Thị trấn Lai Vung": "I",
        "Xã Định Hòa": "II",
        "Xã Hòa Long": "I",
        "Xã Hòa Thành": "I",
        "Xã Long Hậu": "I",
        "Xã Long Thắng": "II",
        "Xã Phong Hòa": "II",
        "Xã Tân Dương": "I",
        "Xã Tân Hòa": "II",
        "Xã Tân Phước": "I",
        "Xã Tân Thành": "I",
        "Xã Vĩnh Thới": "I",
      },
    },
    "Gia Lai": {
      "Thành phố Pleiku": "I",
      "T.Xã An Khê": "I",
      "T.Xã Ayun Pa": "I",
      "Huyện Chư Păh": "I",
      "Huyện Chư Prông": "I",
      "Huyện Chư Pưh": "I",
      "Huyện Chư Sê": "I",
      "Huyện Đăk Đoa": "I",
      "Huyện Đăk Pơ": "I",
      "Huyện Đức Cơ": "I",
      "Huyện Ia Grai": "I",
      "Huyện Ia Pa": "I",
      "Huyện KBang": "I",
      "Huyện Kông Chro": "I",
      "Huyện Krông Pa": "I",
      "Huyện Mang Yang": "I",
      "Huyện Phú Thiện": "I",
    },
    "Hà Giang": {
      "Thành phố Hà Giang": "II",
      "Huyện Bắc Mê": "II",
      "Huyện Bắc Quang": "II",
      "Huyện Đồng Văn": "I",
      "Huyện Hoàng Su Phì": "II",
      "Huyện Mèo Vạc": "I",
      "Huyện Quản Bạ": "I",
      "Huyện Quang Bình": "II",
      "Huyện Vị Xuyên": "I",
      "Huyện Xín Mần": "I",
      "Huyện Yên Minh": "I",
    },
    "Hà Nam": {
      "Thành phố Phủ Lý": "III",
      "T.Xã Duy Tiên": "III",
      "Huyện Bình Lục": "IV",
      "Huyện Kim Bảng": "III",
      "Huyện Lý Nhân": "III",
      "Huyện Thanh Liêm": "III",
    },
    "Hà Tĩnh": {
      "Thành phố Hà Tĩnh": "IV",
      "T.Xã Kỳ Anh": "IV",
      "T.Xã Hồng Lĩnh": "IV",
      "Huyện Can Lộc": "IV",
      "Huyện Đức Thọ": "II",
      "Huyện Kỳ Anh": "IV",
      "Huyện Lộc Hà": "IV",
      "Huyện Nghi Xuân": "IV",
      "Huyện Thạch Hà": "IV",
      "Huyện Vũ Quang": "II",
      "Huyện Cẩm Xuyên": {
        "Thị trấn Cẩm Xuyên": "III",
        "Thị trấn Thiên Cầm": "IV",
        "Xã Cẩm Bình": "III",
        "Xã Cẩm Duệ": "III",
        "Xã Cẩm Dương": "IV",
        "Xã Cẩm Hà": "III",
        "Xã Cẩm Hưng": "III",
        "Xã Cẩm Lạc": "III",
        "Xã Cẩm Lĩnh": "IV",
        "Xã Cẩm Lộc": "IV",
        "Xã Cẩm Minh": "III",
        "Xã Cẩm Mỹ": "III",
        "Xã Cẩm Nhượng": "IV",
        "Xã Cẩm Quan": "III",
        "Xã Cẩm Quang": "III",
        "Xã Cẩm Sơn": "III",
        "Xã Cẩm Thạch": "III",
        "Xã Cẩm Thành": "III",
        "Xã Cẩm Thịnh": "III",
        "Xã Cẩm Trung": "IV",
        "Xã Cẩm Vĩnh": "III",
        "Xã Nam Phúc Thăng": "III",
        "Xã Yên Hòa": "IV",
      },
      "Huyện Hương Khê": {
        "Thị trấn Hương Khê": "II",
        "Xã Điền Mỹ": "II",
        "Xã Gia Phố": "II",
        "Xã Hà Linh": "II",
        "Xã Hòa Hải": "II",
        "Xã Hương Bình": "II",
        "Xã Hương Đô": "II",
        "Xã Hương Giang": "II",
        "Xã Hương Lâm": "I",
        "Xã Hương Liên": "I",
        "Xã Hương Long": "II",
        "Xã Hương Thủy": "II",
        "Xã Hương Trà": "I",
        "Xã Hương Trạch": "II",
        "Xã Hương Vĩnh": "I",
        "Xã Hương Xuân": "I",
        "Xã Lộc Yên": "II",
        "Xã Phú Gia": "I",
        "Xã Phú Phong": "I",
        "Xã Phúc Đồng": "II",
        "Xã Phúc Trạch": "II",
      },
      "Huyện Hương Sơn": {
        "Thị trấn Phố Châu": "II",
        "Thị trấn Tây Sơn": "I",
        "Xã An Hòa Thịnh": "II",
        "Xã Kim Hoa": "II",
        "Xã Quang Diệm": "I",
        "Xã Sơn Bằng": "II",
        "Xã Sơn Bình": "II",
        "Xã Sơn Châu": "II",
        "Xã Sơn Giang": "II",
        "Xã Sơn Hàm": "I",
        "Xã Sơn Hồng": "I",
        "Xã Sơn Kim 1": "I",
        "Xã Sơn Kim 2": "I",
        "Xã Sơn Lâm": "II",
        "Xã Sơn Lễ": "II",
        "Xã Sơn Lĩnh": "I",
        "Xã Sơn Long": "II",
        "Xã Sơn Ninh": "II",
        "Xã Sơn Phú": "II",
        "Xã Sơn Tây": "I",
        "Xã Sơn Tiến": "II",
        "Xã Sơn Trà": "II",
        "Xã Sơn Trung": "II",
        "Xã Sơn Trường": "II",
        "Xã Tân Mỹ Hà": "II",
      },
    },
    "Hải Dương": {
      "Thành phố Hải Dương": "III",
      "Thành phố Chí Linh": "III",
      "T.Xã Kinh Môn": "III",
      "Huyện Bình Giang": "III",
      "Huyện Cẩm Giàng": "III",
      "Huyện Gia Lộc": "III",
      "Huyện Kim Thành": "III",
      "Huyện Nam Sách": "III",
      "Huyện Ninh Giang": "III",
      "Huyện Thanh Hà": "III",
      "Huyện Thanh Miện": "III",
      "Huyện Tứ Kỳ": "IV",
    },
    "Hậu Giang": {
      "Thành phố Vị Thanh": "II",
      "Thành phố Ngã Bảy": "II",
      "T.Xã Long Mỹ": "II",
      "Huyện Châu Thành": "II",
      "Huyện Châu Thành A": "II",
      "Huyện Long Mỹ": "II",
      "Huyện Phụng Hiệp": "II",
      "Huyện Vị Thuỷ": "II",
    },
    "Hoà Bình": {
      "Thành phố Hòa Bình": "II",
      "Huyện Cao Phong": "II",
      "Huyện Kim Bôi": "II",
      "Huyện Lạc Sơn": "II",
      "Huyện Lạc Thủy": "II",
      "Huyện Lương Sơn": "II",
      "Huyện Mai Châu": "I",
      "Huyện Tân Lạc": "II",
      "Huyện Đà Bắc": {
        "Thị trấn Đà Bắc": "II",
        "Xã Cao Sơn": "II",
        "Xã Đoàn Kết": "I",
        "Xã Đồng Chum": "I",
        "Xã Đồng Ruộng": "I",
        "Xã Giáp Đắt": "I",
        "Xã Hiền Lương": "II",
        "Xã Mường Chiềng": "I",
        "Xã Nánh Nghê": "I",
        "Xã Tân Minh": "II",
        "Xã Tân Pheo": "I",
        "Xã Tiền Phong": "I",
        "Xã Toàn Sơn": "II",
        "Xã Trung Thành": "I",
        "Xã Tú Lý": "II",
        "Xã Vầy Nưa": "II",
        "Xã Yên Hòa": "I",
      },
      "Huyện Yên Thủy": {
        "Thị trấn Hàng Trạm": "III",
        "Xã Bảo Hiệu": "III",
        "Xã Đa Phúc": "II",
        "Xã Đoàn Kết": "III",
        "Xã Hữu Lợi": "III",
        "Xã Lạc Lương": "II",
        "Xã Lạc Sỹ": "II",
        "Xã Lạc Thịnh": "II",
        "Xã Ngọc Lương": "III",
        "Xã Phú Lai": "III",
        "Xã Yên Trị": "III",
      },
    },
    "Hưng Yên": {
      "Thành phố Hưng Yên": "III",
      "T.Xã Mỹ Hào": "III",
      "Huyện Ân Thi": "III",
      "Huyện Khoái Châu": "III",
      "Huyện Kim Động": "III",
      "Huyện Phù Cừ": "III",
      "Huyện Tiên Lữ": "III",
      "Huyện Văn Giang": "II",
      "Huyện Văn Lâm": "II",
      "Huyện Yên Mỹ": "III",
    },
    "Khánh Hòa": {
      "Thành phố Nha Trang": "II",
      "Thành phố Cam Ranh": "II",
      "T.Xã Ninh Hòa": "II",
      "Huyện Cam Lâm": "II",
      "Huyện Diên Khánh": "II",
      "Huyện Khánh Sơn": "I",
      "Huyện Khánh Vĩnh": "I",
      "Huyện Trường Sa": "IV",
      "Huyện Vạn Ninh": "II",
    },
    "Kiên Giang": {
      "Thành phố Rạch Giá": "II",
      "Thành phố Hà Tiên": "II",
      "Huyện An Biên": "II",
      "Huyện An Minh": "II",
      "Huyện Châu Thành": "II",
      "Huyện Giang Thành": "II",
      "Huyện Giồng Riềng": "II",
      "Huyện Gò Quao": "II",
      "Huyện Hòn Đất": "II",
      "Huyện Kiên Hải": "III",
      "Huyện Kiên Lương": "II",
      "Huyện Tân Hiệp": "II",
      "Huyện U Minh Thượng": "II",
      "Huyện Vĩnh Thuận": "II",
      "Thành phố Phú Quốc": "III",
    },
    "Kon Tum": {
      "Thành phố Kon Tum": "I",
      "Huyện Đắk Glei": "I",
      "Huyện Đắk Hà": "I",
      "Huyện Đắk Tô": "I",
      "Huyện Ia H' Drai": "I",
      "Huyện Kon Plông": "I",
      "Huyện Kon Rẫy": "I",
      "Huyện Ngọc Hồi": "I",
      "Huyện Sa Thầy": "I",
      "Huyện Tu Mơ Rông": "I",
    },
    "Lai Châu": {
      "Thành phố Lai Châu": "II",
      "Huyện Mường Tè": "II",
      "Huyện Nậm Nhùn": "II",
      "Huyện Phong Thổ": "II",
      "Huyện Sìn Hồ": "II",
      "Huyện Tam Đường": "II",
      "Huyện Tân Uyên": "II",
      "Huyện Than Uyên": "II",
    },
    "Lâm Đồng": {
      "Thành phố Đà Lạt": "I",
      "Thành phố Bảo Lộc": "I",
      "Huyện Bảo Lâm": "I",
      "Huyện Cát Tiên": "I",
      "Huyện Đạ Huoai": "I",
      "Huyện Đạ Tẻh": "I",
      "Huyện Đam Rông": "I",
      "Huyện Di Linh": "I",
      "Huyện Đơn Dương": "I",
      "Huyện Đức Trọng": "I",
      "Huyện Lạc Dương": "I",
      "Huyện Lâm Hà": "I",
    },
    "Lạng Sơn": {
      "Thành phố Lạng Sơn": "I",
      "Huyện Bắc Sơn": "I",
      "Huyện Bình Gia": "I",
      "Huyện Cao Lộc": "I",
      "Huyện Chi Lăng": "I",
      "Huyện Lộc Bình": "I",
      "Huyện Tràng Định": "I",
      "Huyện Văn Lãng": "I",
      "Huyện Văn Quan": "I",
      "Huyện Đình Lập": {
        "Thị trấn Đình Lập": "I",
        "Thị trấn NT Thái Bình": "I",
        "Xã Bắc Lãng": "II",
        "Xã Bắc Xa": "I",
        "Xã Bính Xá": "I",
        "Xã Châu Sơn": "II",
        "Xã Cường Lợi": "I",
        "Xã Đình Lập": "I",
        "Xã Đồng Thắng": "II",
        "Xã Kiên Mộc": "I",
        "Xã Lâm Ca": "II",
        "Xã Thái Bình": "I",
      },
      "Huyện Hữu Lũng": {
        "Thị trấn Hữu Lũng": "I",
        "Xã Cai Kinh": "I",
        "Xã Đồng Tân": "I",
        "Xã Đồng Tiến": "II",
        "Xã Hồ Sơn": "I",
        "Xã Hòa Bình": "I",
        "Xã Hòa Lạc": "I",
        "Xã Hòa Sơn": "I",
        "Xã Hòa Thắng": "II",
        "Xã Hữu Liên": "I",
        "Xã Minh Hòa": "II",
        "Xã Minh Sơn": "II",
        "Xã Minh Tiến": "I",
        "Xã Nhật Tiến": "I",
        "Xã Quyết Thắng": "I",
        "Xã Sơn Hà": "I",
        "Xã Tân Thành": "I",
        "Xã Thanh Sơn": "II",
        "Xã Thiện Tân": "I",
        "Xã Vân Nham": "II",
        "Xã Yên Bình": "I",
        "Xã Yên Sơn": "I",
        "Xã Yên Thịnh": "I",
        "Xã Yên Vượng": "I",
      },
    },
    "Lào Cai": {
      "Thành phố Lào Cai": "I",
      "T.Xã Sa Pa": "II",
      "Huyện Bắc Hà": "I",
      "Huyện Bảo Thắng": "I",
      "Huyện Bảo Yên": "I",
      "Huyện Mường Khương": "I",
      "Huyện Si Ma Cai": "I",
      "Huyện Bát Xát": {
        "Thị trấn Bát Xát": "I",
        "Xã A Lù": "II",
        "Xã A Mú Sung": "II",
        "Xã Bản Qua": "II",
        "Xã Bản Vược": "II",
        "Xã Bản Xèo": "II",
        "Xã Cốc Mỳ": "II",
        "Xã Dền Sáng": "II",
        "Xã Dền Thàng": "II",
        "Xã Mường Hum": "II",
        "Xã Mường Vi": "II",
        "Xã Nậm Chạc": "II",
        "Xã Nậm Pung": "II",
        "Xã Pa Cheo": "II",
        "Xã Phìn Ngan": "II",
        "Xã Quang Kim": "I",
        "Xã Sàng Ma Sáo": "II",
        "Xã Tòng Sành": "I",
        "Xã Trịnh Tường": "II",
        "Xã Trung Lèng Hồ": "II",
        "Xã Y Tý": "II",
      },
      "Huyện Văn Bàn": {
        "Thị trấn Khánh Yên": "I",
        "Xã Chiềng Ken": "I",
        "Xã Dần Thàng": "II",
        "Xã Dương Quỳ": "II",
        "Xã Hoà Mạc": "II",
        "Xã Khánh Yên Hạ": "II",
        "Xã Khánh Yên Thượng": "I",
        "Xã Khánh Yên Trung": "II",
        "Xã Làng Giàng": "I",
        "Xã Liêm Phú": "I",
        "Xã Minh Lương": "II",
        "Xã Nậm Chầy": "II",
        "Xã Nậm Mả": "II",
        "Xã Nậm Rạng": "I",
        "Xã Nậm Tha": "I",
        "Xã Nậm Xây": "II",
        "Xã Nậm Xé": "II",
        "Xã Sơn Thuỷ": "I",
        "Xã Tân An": "I",
        "Xã Tân Thượng": "I",
        "Xã Thẩm Dương": "II",
        "Xã Võ Lao": "I",
      },
    },
    "Long An": {
      "Thành phố Tân An": "II",
      "T.Xã Kiến Tường": "I",
      "Huyện Bến Lức": "II",
      "Huyện Cần Đước": "II",
      "Huyện Cần Giuộc": "II",
      "Huyện Châu Thành": "II",
      "Huyện Đức Hòa": "I",
      "Huyện Đức Huệ": "I",
      "Huyện Mộc Hóa": "I",
      "Huyện Tân Hưng": "I",
      "Huyện Tân Thạnh": "I",
      "Huyện Tân Trụ": "II",
      "Huyện Thạnh Hóa": "I",
      "Huyện Thủ Thừa": "II",
      "Huyện Vĩnh Hưng": "I",
    },
    "Nam Định": {
      "Thành phố Nam Định": "IV",
      "Huyện Giao Thủy": "IV",
      "Huyện Hải Hậu": "IV",
      "Huyện Mỹ Lộc": "IV",
      "Huyện Nam Trực": "IV",
      "Huyện Nghĩa Hưng": "IV",
      "Huyện Trực Ninh": "IV",
      "Huyện Vụ Bản": "IV",
      "Huyện Xuân Trường": "IV",
      "Huyện Ý Yên": "IV",
    },
    "Nghệ An": {
      "Thành phố Vinh": "III",
      "T.Xã Cửa Lò": "IV",
      "T.Xã Hoàng Mai": "IV",
      "T.Xã Thái Hoà": "III",
      "Huyện Anh Sơn": "II",
      "Huyện Con Cuông": "I",
      "Huyện Diễn Châu": "III",
      "Huyện Đô Lương": "II",
      "Huyện Hưng Nguyên": "III",
      "Huyện Kỳ Sơn": "I",
      "Huyện Nam Đàn": "II",
      "Huyện Nghi Lộc": "III",
      "Huyện Quế Phong": "I",
      "Huyện Quỳ Hợp": "II",
      "Huyện Tân Kỳ": "II",
      "Huyện Thanh Chương": "II",
      "Huyện Tương Dương": "I",
      "Huyện Nghĩa Đàn": {
        "Thị trấn Nghĩa Đàn": "III",
        "Xã Nghĩa An": "II",
        "Xã Nghĩa Bình": "III",
        "Xã Nghĩa Đức": "II",
        "Xã Nghĩa Hiếu": "II",
        "Xã Nghĩa Hội": "III",
        "Xã Nghĩa Hồng": "II",
        "Xã Nghĩa Hưng": "II",
        "Xã Nghĩa Khánh": "II",
        "Xã Nghĩa Lạc": "III",
        "Xã Nghĩa Lâm": "III",
        "Xã Nghĩa Lộc": "III",
        "Xã Nghĩa Lợi": "III",
        "Xã Nghĩa Long": "III",
        "Xã Nghĩa Mai": "II",
        "Xã Nghĩa Minh": "II",
        "Xã Nghĩa Phú": "III",
        "Xã Nghĩa Sơn": "III",
        "Xã Nghĩa Thành": "II",
        "Xã Nghĩa Thịnh": "II",
        "Xã Nghĩa Thọ": "III",
        "Xã Nghĩa Trung": "III",
        "Xã Nghĩa Yên": "II",
      },
      "Huyện Quỳ Châu": {
        "Thị trấn Tân Lạc": "I",
        "Xã Châu Bính": "II",
        "Xã Châu Bình": "I",
        "Xã Châu Hạnh": "II",
        "Xã Châu Hoàn": "I",
        "Xã Châu Hội": "II",
        "Xã Châu Nga": "II",
        "Xã Châu Phong": "I",
        "Xã Châu Thắng": "I",
        "Xã Châu Thuận": "I",
        "Xã Châu Tiến": "I",
        "Xã Diên Lãm": "I",
      },
      "Huyện Quỳnh Lưu": {
        "Thị trấn Cầu Giát": "III",
        "Xã An Hòa": "IV",
        "Xã Ngọc Sơn": "III",
        "Xã Quỳnh Bá": "III",
        "Xã Quỳnh Bảng": "IV",
        "Xã Quỳnh Châu": "III",
        "Xã Quỳnh Diễn": "III",
        "Xã Quỳnh Đôi": "IV",
        "Xã Quỳnh Giang": "III",
        "Xã Quỳnh Hậu": "III",
        "Xã Quỳnh Hoa": "III",
        "Xã Quỳnh Hồng": "III",
        "Xã Quỳnh Hưng": "III",
        "Xã Quỳnh Lâm": "III",
        "Xã Quỳnh Long": "IV",
        "Xã Quỳnh Lương": "IV",
        "Xã Quỳnh Minh": "IV",
        "Xã Quỳnh Mỹ": "III",
        "Xã Quỳnh Nghĩa": "IV",
        "Xã Quỳnh Ngọc": "III",
        "Xã Quỳnh Tam": "III",
        "Xã Quỳnh Tân": "III",
        "Xã Quỳnh Thạch": "III",
        "Xã Quỳnh Thắng": "III",
        "Xã Quỳnh Thanh": "IV",
        "Xã Quỳnh Thọ": "III",
        "Xã Quỳnh Thuận": "IV",
        "Xã Quỳnh Văn": "III",
        "Xã Quỳnh Yên": "IV",
        "Xã Sơn Hải": "III",
        "Xã Tân Sơn": "III",
        "Xã Tân Thắng": "III",
        "Xã Tiến Thủy": "IV",
      },
      "Huyện Yên Thành": {
        "Thị trấn Yên Thành": "II",
        "Xã Bắc Thành": "II",
        "Xã Bảo Thành": "II",
        "Xã Công Thành": "II",
        "Xã Đại Thành": "II",
        "Xã Đô Thành": "III",
        "Xã Đồng Thành": "II",
        "Xã Đức Thành": "III",
        "Xã Hậu Thành": "III",
        "Xã Hoa Thành": "III",
        "Xã Hồng Thành": "III",
        "Xã Hợp Thành": "III",
        "Xã Hùng Thành": "II",
        "Xã Khánh Thành": "II",
        "Xã Kim Thành": "II",
        "Xã Lăng Thành": "III",
        "Xã Liên Thành": "II",
        "Xã Long Thành": "II",
        "Xã Lý Thành": "II",
        "Xã Mã Thành": "III",
        "Xã Minh Thành": "II",
        "Xã Mỹ Thành": "II",
        "Xã Nam Thành": "II",
        "Xã Nhân Thành": "III",
        "Xã Phú Thành": "III",
        "Xã Phúc Thành": "III",
        "Xã Quang Thành": "II",
        "Xã Sơn Thành": "III",
        "Xã Tân Thành": "III",
        "Xã Tăng Thành": "II",
        "Xã Tây Thành": "II",
        "Xã Thịnh Thành": "II",
        "Xã Thọ Thành": "III",
        "Xã Tiến Thành": "III",
        "Xã Trung Thành": "II",
        "Xã Văn Thành": "III",
        "Xã Viên Thành": "III",
        "Xã Vĩnh Thành": "III",
        "Xã Xuân Thành": "II",
      },
    },
    "Ninh Bình": {
      "Thành phố Ninh Bình": "IV",
      "Thành phố Tam Điệp": "IV",
      "Huyện Gia Viễn": "III",
      "Huyện Hoa Lư": "III",
      "Huyện Kim Sơn": "IV",
      "Huyện Nho Quan": "III",
      "Huyện Yên Khánh": "IV",
      "Huyện Yên Mô": "IV",
    },
    "Ninh Thuận": {
      "Thành phố Phan Rang-Tháp Chàm": "II",
      "Huyện Bác Ái": "I",
      "Huyện Ninh Hải": "II",
      "Huyện Ninh Phước": "II",
      "Huyện Ninh Sơn": "I",
      "Huyện Thuận Bắc": "II",
      "Huyện Thuận Nam": "II",
    },
    "Phú Thọ": {
      "Thành phố Việt Trì": "II",
      "T.Xã Phú Thọ": "II",
      "Huyện Cẩm Khê": "II",
      "Huyện Đoan Hùng": "II",
      "Huyện Hạ Hoà": "II",
      "Huyện Lâm Thao": "II",
      "Huyện Phù Ninh": "II",
      "Huyện Tam Nông": "II",
      "Huyện Tân Sơn": "II",
      "Huyện Thanh Ba": "II",
      "Huyện Thanh Sơn": "II",
      "Huyện Thanh Thuỷ": "II",
      "Huyện Yên Lập": "II",
    },
    "Phú Yên": {
      "Thành phố Tuy Hoà": "III",
      "T.Xã Sông Cầu": "III",
      "Huyện Phú Hoà": "III",
      "Huyện Sơn Hòa": "II",
      "Huyện Sông Hinh": "II",
      "Huyện Tuy An": "III",
      "T.Xã Đông Hòa": "III",
      "Huyện Đồng Xuân": {
        "Thị trấn La Hai": "III",
        "Xã Đa Lộc": "III",
        "Xã Phú Mỡ": "II",
        "Xã Xuân Lãnh": "III",
        "Xã Xuân Long": "III",
        "Xã Xuân Phước": "II",
        "Xã Xuân Quang 1": "II",
        "Xã Xuân Quang 2": "II",
        "Xã Xuân Quang 3": "II",
        "Xã Xuân Sơn Bắc": "III",
        "Xã Xuân Sơn Nam": "III",
      },
      "Huyện Tây Hoà": {
        "Thị trấn Phú Thứ": "III",
        "Xã Hòa Bình 1": "III",
        "Xã Hòa Đồng": "III",
        "Xã Hòa Mỹ Đông": "II",
        "Xã Hòa Mỹ Tây": "II",
        "Xã Hòa Phong": "II",
        "Xã Hòa Phú": "II",
        "Xã Hòa Tân Tây": "III",
        "Xã Hòa Thịnh": "III",
        "Xã Sơn Thành Đông": "II",
        "Xã Sơn Thành Tây": "II",
      },
    },
    "Quảng Bình": {
      "Thành phố Đồng Hới": "III",
      "T.Xã Ba Đồn": "III",
      "Huyện Minh Hóa": "I",
      "Huyện Quảng Ninh": "III",
      "Huyện Quảng Trạch": "III",
      "Huyện Tuyên Hóa": "II",
      "Huyện Bố Trạch": {
        "Thị trấn Hoàn Lão": "II",
        "Thị trấn NT Việt Trung": "II",
        "Thị trấn Phong Nha": "II",
        "Xã Bắc Trạch": "III",
        "Xã Cự Nẫm": "II",
        "Xã Đại Trạch": "III",
        "Xã Đồng Trạch": "III",
        "Xã Đức Trạch": "III",
        "Xã Hạ Trạch": "II",
        "Xã Hải Phú": "III",
        "Xã Hòa Trạch": "II",
        "Xã Hưng Trạch": "II",
        "Xã Lâm Trạch": "II",
        "Xã Liên Trạch": "II",
        "Xã Lý Trạch": "III",
        "Xã Mỹ Trạch": "II",
        "Xã Nam Trạch": "II",
        "Xã Nhân Trạch": "III",
        "Xã Phú Định": "II",
        "Xã Phúc Trạch": "II",
        "Xã Sơn Lộc": "II",
        "Xã Tân Trạch": "II",
        "Xã Tây Trạch": "II",
        "Xã Thanh Trạch": "III",
        "Xã Thượng Trạch": "II",
        "Xã Trung Trạch": "III",
        "Xã Vạn Trạch": "II",
        "Xã Xuân Trạch": "II",
      },
      "Huyện Lệ Thủy": {
        "Thị trấn Kiến Giang": "II",
        "Thị trấn NT Lệ Ninh": "II",
        "Xã An Thủy": "II",
        "Xã Cam Thủy": "II",
        "Xã Dương Thủy": "II",
        "Xã Hoa Thủy": "II",
        "Xã Hồng Thủy": "II",
        "Xã Hưng Thủy": "II",
        "Xã Kim Thủy": "II",
        "Xã Lâm Thủy": "II",
        "Xã Liên Thủy": "II",
        "Xã Lộc Thủy": "II",
        "Xã Mai Thủy": "II",
        "Xã Mỹ Thủy": "II",
        "Xã Ngân Thủy": "II",
        "Xã Ngư Thủy ": "III",
        "Xã Ngư Thủy Bắc": "III",
        "Xã Phong Thủy": "II",
        "Xã Phú Thủy": "II",
        "Xã Sen Thủy": "III",
        "Xã Sơn Thủy": "II",
        "Xã Tân Thủy": "II",
        "Xã Thái Thủy": "II",
        "Xã Thanh Thủy": "II",
        "Xã Trường Thủy": "II",
        "Xã Xuân Thủy": "II",
      },
    },
    "Quảng Nam": {
      "Thành phố Tam Kỳ": "III",
      "Thành phố Hội An": "III",
      "T.Xã Điện Bàn": "III",
      "Huyện Đại Lộc": "II",
      "Huyện Đông Giang": "I",
      "Huyện Hiệp Đức": "II",
      "Huyện Nam Giang": "I",
      "Huyện Nam Trà My": "I",
      "Huyện Nông Sơn": "II",
      "Huyện Núi Thành": "III",
      "Huyện Phước Sơn": "I",
      "Huyện Tây Giang": "I",
      "Huyện Thăng Bình": "III",
      "Huyện Tiên Phước": "II",
      "Huyện Bắc Trà My": {
        "Thị trấn Trà My": "II",
        "Xã Trà Bui": "I",
        "Xã Trà Đốc": "I",
        "Xã Trà Đông": "II",
        "Xã Trà Dương": "II",
        "Xã Trà Giác": "II",
        "Xã Trà Giang": "II",
        "Xã Trà Giáp": "II",
        "Xã Trà Ka": "II",
        "Xã Trà Kót": "II",
        "Xã Trà Nú": "II",
        "Xã Trà Sơn": "I",
        "Xã Trà Tân": "I",
      },
      "Huyện Duy Xuyên": {
        "Thị trấn Nam Phước": "III",
        "Xã Duy Châu": "II",
        "Xã Duy Hải": "III",
        "Xã Duy Hòa": "II",
        "Xã Duy Nghĩa": "III",
        "Xã Duy Phú": "II",
        "Xã Duy Phước": "III",
        "Xã Duy Sơn": "II",
        "Xã Duy Tân": "II",
        "Xã Duy Thành": "III",
        "Xã Duy Thu": "II",
        "Xã Duy Trinh": "II",
        "Xã Duy Trung": "III",
        "Xã Duy Vinh": "III",
      },
      "Huyện Phú Ninh": {
        "Thị trấn Phú Thịnh": "II",
        "Xã Tam An": "III",
        "Xã Tam Đại": "III",
        "Xã Tam Dân": "II",
        "Xã Tam Đàn": "III",
        "Xã Tam Lãnh": "II",
        "Xã Tam Lộc": "II",
        "Xã Tam Phước": "II",
        "Xã Tam Thái": "II",
        "Xã Tam Thành": "III",
        "Xã Tam Vinh": "II",
      },
      "Huyện Quế Sơn": {
        "Thị trấn Đông Phú": "II",
        "Thị trấn Hương An": "III",
        "Xã Quế An": "II",
        "Xã Quế Châu": "II",
        "Xã Quế Hiệp": "II",
        "Xã Quế Long": "II",
        "Xã Quế Minh": "II",
        "Xã Quế Mỹ": "III",
        "Xã Quế Phong": "II",
        "Xã Quế Phú": "III",
        "Xã Quế Thuận": "II",
        "Xã Quế Xuân 1": "III",
        "Xã Quế Xuân 2": "III",
      },
    },
    "Quảng Ngãi": {
      "Thành phố Quảng Ngãi": "III",
      "T.Xã Đức Phổ": "III",
      "Huyện Ba Tơ": "II",
      "Huyện Bình Sơn": "III",
      "Huyện Lý Sơn": "III",
      "Huyện Minh Long": "II",
      "Huyện Mộ Đức": "III",
      "Huyện Nghĩa Hành": "III",
      "Huyện Sơn Hà": "II",
      "Huyện Sơn Tịnh": "III",
      "Huyện Trà Bồng": "II",
      "Huyện Tư Nghĩa": "III",
      "Huyện Sơn Tây": {
        "Xã Sơn Bua": "I",
        "Xã Sơn Dung": "I",
        "Xã Sơn Lập": "II",
        "Xã Sơn Liên": "I",
        "Xã Sơn Long": "I",
        "Xã Sơn Màu": "II",
        "Xã Sơn Mùa": "I",
        "Xã Sơn Tân": "II",
        "Xã Sơn Tinh": "II",
      },
    },
    "Quảng Ninh": {
      "Thành phố Hạ Long": "III",
      "Thành phố Móng Cái": "III",
      "Thành phố Cẩm Phả": "III",
      "Thành phố Uông Bí": "III",
      "T.Xã Quảng Yên": "IV",
      "T.Xã Đông Triều": "III",
      "Huyện Ba Chẽ": "III",
      "Huyện Bình Liêu": "II",
      "Huyện Cô Tô": "IV",
      "Huyện Đầm Hà": "III",
      "Huyện Hải Hà": "III",
      "Huyện Tiên Yên": "III",
      "Huyện Vân Đồn": "IV",
    },
    "Quảng Trị": {
      "Thành phố Đông Hà": "II",
      "T.Xã Quảng Trị": "II",
      "Huyện Cam Lộ": "II",
      "Huyện Cồn Cỏ": "III",
      "Huyện Đa Krông": "II",
      "Huyện Gio Linh": "III",
      "Huyện Hải Lăng": "II",
      "Huyện Hướng Hóa": "I",
      "Huyện Triệu Phong": "III",
      "Huyện Vĩnh Linh": "III",
    },
    "Sóc Trăng": {
      "Thành phố Sóc Trăng": "II",
      "Huyện Châu Thành": "II",
      "Huyện Cù Lao Dung": "II",
      "Huyện Kế Sách": "II",
      "Huyện Long Phú": "II",
      "Huyện Mỹ Tú": "II",
      "Huyện Mỹ Xuyên": "II",
      "Huyện Thạnh Trị": "II",
      "Huyện Trần Đề": "II",
      "T.Xã Ngã Năm": "II",
      "T.Xã Vĩnh Châu": "II",
    },
    "Sơn La": {
      "Thành phố Sơn La": "II",
      "Huyện Bắc Yên": "II",
      "Huyện Mai Sơn": "II",
      "Huyện Mộc Châu": "II",
      "Huyện Mường La": "II",
      "Huyện Phù Yên": "II",
      "Huyện Quỳnh Nhai": "II",
      "Huyện Sông Mã": "II",
      "Huyện Sốp Cộp": "II",
      "Huyện Thuận Châu": "II",
      "Huyện Vân Hồ": "II",
      "Huyện Yên Châu": "II",
    },
    "Tây Ninh": {
      "Thành phố Tây Ninh": "I",
      "T.Xã Trảng Bàng": "I",
      "T.Xã Hòa Thành": "I",
      "Huyện Bến Cầu": "I",
      "Huyện Châu Thành": "I",
      "Huyện Dương Minh Châu": "I",
      "Huyện Gò Dầu": "I",
      "Huyện Tân Biên": "I",
      "Huyện Tân Châu": "I",
    },
    "Thái Bình": {
      "Thành phố Thái Bình": "I",
      "Huyện Đông Hưng": "I",
      "Huyện Hưng Hà": "I",
      "Huyện Kiến Xương": "I",
      "Huyện Quỳnh Phụ": "I",
      "Huyện Thái Thụy": "I",
      "Huyện Tiền Hải": "I",
      "Huyện Vũ Thư": "I",
    },
    "Thái Nguyên": {
      "Thành phố Thái Nguyên": "II",
      "Thành phố Sông Công": "II",
      "T.Xã Phổ Yên": "II",
      "Huyện Võ Nhai": "I",
      "Huyện Phú Lương": "I",
      "Huyện Phú Bình": "II",
      "Huyện Định Hóa": "II",
      "Huyện Đại Từ": "II",
      "Huyện Đồng Hỷ": {
        "Thị trấn Sông Cầu": "I",
        "Thị trấn Trại Cau": "II",
        "Xã Cây Thị": "I",
        "Xã Hòa Bình": "I",
        "Xã Hóa Thượng": "I",
        "Xã Hóa Trung": "I",
        "Xã Hợp Tiến": "II",
        "Xã Khe Mo": "I",
        "Xã Minh Lập": "I",
        "Xã Nam Hòa": "II",
        "Xã Quang Sơn": "I",
        "Xã Tân Lợi": "II",
        "Xã Tân Long": "I",
        "Xã Văn Hán": "I",
        "Xã Văn Lăng": "I",
      },
    },
    "Thanh Hóa": {
      "Thành phố Thanh Hóa": "IV",
      "Thành phố Sầm Sơn": "IV",
      "T.Xã Nghi Sơn": "IV",
      "T.Xã Bỉm Sơn": "IV",
      "Huyện Bá Thước": "II",
      "Huyện Cẩm Thủy": "II",
      "Huyện Đông Sơn": "III",
      "Huyện Hậu Lộc": "IV",
      "Huyện Hoằng Hóa": "IV",
      "Huyện Lang Chánh": "II",
      "Huyện Mường Lát": "I",
      "Huyện Nga Sơn": "IV",
      "Huyện Ngọc Lặc": "II",
      "Huyện Như Thanh": "II",
      "Huyện Như Xuân": "II",
      "Huyện Nông Cống": "III",
      "Huyện Quan Hóa": "I",
      "Huyện Quan Sơn": "I",
      "Huyện Quảng Xương": "III",
      "Huyện Thạch Thành": "III",
      "Huyện Thiệu Hóa": "III",
      "Huyện Thọ Xuân": "III",
      "Huyện Thường Xuân": "II",
      "Huyện Triệu Sơn": "III",
      "Huyện Vĩnh Lộc": "III",
      "Huyện Yên Định": "III",
      "Huyện Hà Trung": {
        "Thị trấn Hà Trung": "III",
        "Xã Hà Bắc": "III",
        "Xã Hà Bình": "III",
        "Xã Hà Châu": "III",
        "Xã Hà Đông": "III",
        "Xã Hà Giang": "III",
        "Xã Hà Hải": "IV",
        "Xã Hà Lai": "III",
        "Xã Hà Lĩnh": "III",
        "Xã Hà Long": "III",
        "Xã Hà Ngọc": "III",
        "Xã Hà Sơn": "III",
        "Xã Hà Tân": "III",
        "Xã Hà Thái": "III",
        "Xã Hà Tiến": "III",
        "Xã Hà Vinh": "IV",
        "Xã Hoạt Giang": "III",
        "Xã Lĩnh Toại": "IV",
        "Xã Yên Dương": "III",
        "Xã Yến Sơn": "III",
      },
    },
    "Thừa Thiên Huế": {
      "Thành phố Huế": "II",
      "T.Xã Hương Trà": "II",
      "T.Xã Hương Thủy": "II",
      "Huyện A Lưới": "I",
      "Huyện Phong Điền": "III",
      "Huyện Phú Vang": "III",
      "Huyện Quảng Điền": "III",
      "Huyện Nam Đông": {
        "Thị trấn Khe Tre": "I",
        "Xã Hương Hữu": "I",
        "Xã Hương Lộc": "II",
        "Xã Hương Phú": "II",
        "Xã Hương Sơn": "I",
        "Xã Hương Xuân": "I",
        "Xã Thượng Lộ": "II",
        "Xã Thượng Long": "I",
        "Xã Thượng Nhật": "I",
        "Xã Thượng Quảng": "I",
      },
      "Huyện Phú Lộc": {
        "Thị trấn Lăng Cô": "III",
        "Thị trấn Phú Lộc": "II",
        "Xã Giang Hải": "III",
        "Xã Lộc An": "II",
        "Xã Lộc Bình": "III",
        "Xã Lộc Bổn": "II",
        "Xã Lộc Điền": "II",
        "Xã Lộc Hòa": "II",
        "Xã Lộc Sơn": "II",
        "Xã Lộc Thủy": "III",
        "Xã Lộc Tiến": "III",
        "Xã Lộc Trì": "II",
        "Xã Lộc Vĩnh": "III",
        "Xã Vinh Hiền": "III",
        "Xã Vinh Hưng": "II",
        "Xã Vinh Mỹ": "III",
        "Xã Xuân Lộc": "II",
      },
    },
    "Tiền Giang": {
      "Thành phố Mỹ Tho": "II",
      "T.Xã Gò Công": "II",
      "T.Xã Cai Lậy": "II",
      "Huyện Cái Bè": "II",
      "Huyện Cai Lậy": "II",
      "Huyện Châu Thành": "II",
      "Huyện Chợ Gạo": "II",
      "Huyện Gò Công Đông": "II",
      "Huyện Gò Công Tây": "II",
      "Huyện Tân Phú Đông": "II",
      "Huyện Tân Phước": "II",
    },
    "Trà Vinh": {
      "Thành phố Trà Vinh": "II",
      "Huyện Càng Long": "II",
      "Huyện Cầu Kè": "II",
      "Huyện Cầu Ngang": "II",
      "Huyện Châu Thành": "II",
      "Huyện Duyên Hải": "II",
      "Huyện Tiểu Cần": "II",
      "Huyện Trà Cú": "II",
      "T.Xã Duyên Hải": "II",
    },
    "Tuyên Quang": {
      "Thành phố Tuyên Quang": "II",
      "Huyện Chiêm Hóa": "II",
      "Huyện Hàm Yên": "II",
      "Huyện Lâm Bình": "II",
      "Huyện Na Hang": "II",
      "Huyện Sơn Dương": "I",
      "Huyện Yên Sơn": "II",
    },
    "Vĩnh Long": {
      "Thành phố Vĩnh Long": "II",
      "Huyện Bình Tân": "II",
      "Huyện Long Hồ": "II",
      "Huyện Mang Thít": "II",
      "Huyện Tam Bình": "II",
      "Huyện Trà Ôn": "II",
      "Huyện Vũng Liêm": "II",
      "T.Xã Bình Minh": "II",
    },
    "Vĩnh Phúc": {
      "Thành phố Vĩnh Yên": "II",
      "Thành phố Phúc Yên": "II",
      "Huyện Bình Xuyên": "II",
      "Huyện Lập Thạch": "II",
      "Huyện Sông Lô": "II",
      "Huyện Tam Đảo": "II",
      "Huyện Tam Dương": "II",
      "Huyện Vĩnh Tường": "II",
      "Huyện Yên Lạc": "II",
    },
    "Yên Bái": {
      "Thành phố Yên Bái": "II",
      "T.Xã Nghĩa Lộ": "II",
      "Huyện Lục Yên": "I",
      "Huyện Mù Căng Chải": "II",
      "Huyện Trạm Tấu": "II",
      "Huyện Trấn Yên": "II",
      "Huyện Văn Yên": "I",
      "Huyện Yên Bình": "II",
      "Huyện Văn Chấn": {
        "Thị trấn NT Liên Sơn": "II",
        "Thị trấn NT Trần Phú": "I",
        "Thị trấn Sơn Thịnh": "II",
        "Xã An Lương": "I",
        "Xã Bình Thuận": "I",
        "Xã Cát Thịnh": "II",
        "Xã Chấn Thịnh": "I",
        "Xã Đại Lịch": "I",
        "Xã Đồng Khê": "I",
        "Xã Gia Hội": "II",
        "Xã Minh An": "I",
        "Xã Nậm Búng": "II",
        "Xã Nậm Lành": "II",
        "Xã Nậm Mười": "I",
        "Xã Nghĩa Sơn": "II",
        "Xã Nghĩa Tâm": "I",
        "Xã Sơn Lương": "II",
        "Xã Sùng Đô": "I",
        "Xã Suối Bu": "I",
        "Xã Suối Giàng": "I",
        "Xã Suối Quyền": "I",
        "Xã Tân Thịnh": "I",
        "Xã Thượng Bằng La": "I",
        "Xã Tú Lệ": "II",
      },
    },
  };

export default optionTinh;